name: Deploy to Liberation Staging

on:
  push:
    branches:
      - main

jobs:
  update_server:
    runs-on: sh-jb-1

    steps:
    - uses: actions/checkout@v2
    
    - name: Stop App
      run: |
        docker stop liberation

    - name: Fetch Updates and Restart App
      run: |
        cd ~/Liberation
        git pull
        docker compose up -d --build

    - name: Send Commit done Message
      uses: tsickert/discord-webhook@v5.4.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        embed-title: Liberation Staging is now on commit `${{ github.sha }}`!
        embed-description: |
          Commit Message: ${{ github.event.head_commit.message }}
          Author: ${{ github.triggering_actor }}

    - name: Send Commit done Message on Roc testing server
      uses: tsickert/discord-webhook@v5.4.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL_ROC }}
        embed-title: Liberation Staging is now on commit `${{ github.sha }}`!
        embed-description: |
          Commit Message: ${{ github.event.head_commit.message }}
          Author: ${{ github.triggering_actor }}
      
  
